In [1]:
# ============================================================
# GERANDO UMA MASSA DE DADOS DESBALANCEADA
# Objetivo:
# Simular um dataset para estudos de:
# - Oversampling
# - Undersampling
# - SMOTE
# - Classificação desbalanceada
# ============================================================
import pandas as pd
import numpy as np
from sklearn.datasets import make_classification

 
#  CONFIGURAÇÃO DO DATASET

In [2]:
X, y = make_classification(
    n_samples=10000,          # quantidade total de registros
    n_features=10,            # número total de variáveis
    n_informative=6,          # variáveis realmente importantes
    n_redundant=2,            # variáveis redundantes
    n_repeated=0,
    n_classes=2,              # classificação binária
    weights=[0.80, 0.20],     # DESBALANCEAMENTO
    flip_y=0.01,              # pequeno ruído
    random_state=42
)

# TRANSFORMANDO EM DATAFRAME

In [3]:
colunas = [f'feature_{i}' for i in range(1, 11)]
dataset = pd.DataFrame(X, columns=colunas)
# variável alvo
dataset['inadimplente'] = y

# VISUALIZAÇÃO INICIAL

In [4]:
dataset.head()

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,inadimplente
0,-2.187487,-1.447624,-2.288510,1.056081,0.227333,-0.060147,-1.367876,0.627201,2.518529,-0.376131,0
1,0.028729,0.972903,-0.302152,0.408143,0.283663,0.109245,-0.356853,-1.255259,-1.953986,-2.798042,0
2,1.402790,2.192526,0.658497,0.631485,1.106866,-0.843229,0.188334,-1.145284,-2.836721,-3.579858,1
3,0.895957,0.663586,0.549948,-1.324490,0.714363,2.226197,-1.680641,-0.157837,-4.041746,-1.662902,0
4,1.532724,3.085354,-1.899169,-1.144469,-1.105577,3.233514,-2.509374,-1.055282,-2.406049,0.488451,0

In [5]:
print('\nDistribuição da variável alvo:\n')
print(dataset['inadimplente'].value_counts())

Distribuição da variável alvo:

inadimplente
0    7972
1    2028
Name: count, dtype: int64

In [6]:
print('\nDistribuição percentual:\n')
print(dataset['inadimplente'].value_counts(normalize=True) * 100)

Distribuição percentual:

inadimplente
0    79.72
1    20.28
Name: proportion, dtype: float64

In [9]:
# Esta função calcula a prevalência da classe positiva (label = 1)
def calcula_prevalencia(y_actual):
    return sum(y_actual) / len(y_actual)  # Calcula a prevalência dividindo a soma dos valores em y_atual pelo número total de elementos em y_atual

In [11]:
# Imprime a prevalência da classe positiva no DataFrame df_dsa["LABEL_TARGET"].values com três casas decimais
print("Prevalência da classe positiva: %.3f" % calcula_prevalencia(dataset["inadimplente"].values))

Prevalência da classe positiva: 0.203

# Divisão dos Dados Mantendo a Prevalência de Classe

In [13]:
dados_aleatorios = dataset.sample(n=len(dataset))
dados_aleatorios.head(20)

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,inadimplente
7289,-0.719533,-0.691038,0.761763,-4.032675,1.085951,-1.991875,0.021673,0.642843,-0.831662,-1.735246,0
3490,-1.187694,2.016877,-2.325873,2.232263,-0.100495,0.913172,0.961539,0.450509,-0.711584,-2.387408,0
63,-3.288141,-3.002765,1.734425,-4.859532,0.876060,-1.865061,2.161131,-1.539385,-2.392242,-3.691005,0
5782,0.946686,-0.155564,0.130065,-1.052570,-0.070062,-3.124882,-1.670542,0.554415,2.325177,-0.172315,0
207,1.728404,2.261186,0.641523,-0.719450,0.507272,0.143377,0.137035,0.327038,-2.462135,-1.140497,1
4030,0.041798,0.515756,1.621902,0.203132,0.907173,-1.075282,3.121211,-0.591353,-1.415202,-1.250720,1
9579,0.373615,2.283602,-1.770420,0.199115,0.388916,2.181015,-0.993363,-1.655052,-1.686858,-0.611059,0
4541,0.002484,-0.523933,-1.690523,1.712888,0.314294,-0.337127,-2.902208,2.245961,2.538581,0.231245,0
2777,1.123052,-0.155910,0.163546,-0.942973,0.656824,0.005354,-2.398082,-0.987445,-0.010189,0.386694,0
6040,-1.574510,-1.462464,-0.940309,-0.318808,-0.614839,-0.928069,-0.682342,-0.169421,1.748383,-0.474336,0
276,0.512190,1.327195,-0.649785,2.500162,0.368892,0.569495,0.694045,0.304668,0.352276,0.288770,0
4237,1.998809,2.322375,2.459221,-1.092130,0.147588,1.138248,1.265586,0.214491,-6.407337,-3.370286,1
7046,-2.993805,-2.952606,-1.426234,0.753153,-0.366495,2.941261,-2.065714,-0.458179,-1.209402,-1.808629,0
3454,0.623113,1.307322,-0.918132,-0.950698,0.391710,1.390754,-2.630992,1.784254,-2.729690,-2.373452,0
19,-5.660398,-0.638402,-4.930023,-1.451678,-0.117299,-1.524112,1.656181,0.628208,4.178713,-1.391054,0
2373,-1.793105,0.614409,-2.458494,-1.855843,-0.007538,3.224278,-0.911752,-0.236500,-1.664623,-0.179075,1
6540,-3.821753,-2.697886,-0.955834,-1.376591,1.216813,-0.217440,0.652984,0.153010,0.120838,-2.268341,0
1632,-3.690852,-2.304087,-0.118707,-3.447347,-0.974268,-2.360453,2.202398,0.025081,0.535444,-2.317990,0
3668,-0.974017,-0.130509,-1.593950,-0.868969,0.029308,-2.332956,-0.456130,-1.010114,3.322569,0.278632,0
8058,0.470855,0.701897,0.724709,1.060222,-1.470663,-1.330751,1.781676,1.129191,0.295829,-0.374880,1

In [15]:
dados_aleatorios = dados_aleatorios.reset_index(drop=True)
dados_aleatorios

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,inadimplente
0,-0.719533,-0.691038,0.761763,-4.032675,1.085951,-1.991875,0.021673,0.642843,-0.831662,-1.735246,0
1,-1.187694,2.016877,-2.325873,2.232263,-0.100495,0.913172,0.961539,0.450509,-0.711584,-2.387408,0
2,-3.288141,-3.002765,1.734425,-4.859532,0.876060,-1.865061,2.161131,-1.539385,-2.392242,-3.691005,0
3,0.946686,-0.155564,0.130065,-1.052570,-0.070062,-3.124882,-1.670542,0.554415,2.325177,-0.172315,0
4,1.728404,2.261186,0.641523,-0.719450,0.507272,0.143377,0.137035,0.327038,-2.462135,-1.140497,1
...,...,...,...,...,...,...,...,...,...,...,...
9995,-5.146343,-2.436285,-2.180626,-1.852287,-0.661105,-0.024532,1.272027,0.020640,0.333536,-2.809605,0
9996,0.706287,0.601900,2.013145,-0.632078,-0.536138,0.966317,1.164411,-0.718693,-4.546350,-2.517587,1
9997,0.945049,-0.675383,0.942644,-0.826297,-0.220217,-0.478800,-1.277954,-0.819377,0.109616,0.568758,0
9998,-4.443243,-1.112835,-3.946743,-0.328880,-0.558723,1.318615,-0.019070,0.766316,1.738864,-0.942665,0
9999,1.610990,0.779656,-0.390315,0.726090,-0.361836,0.624027,-2.333579,1.576252,0.216983,0.749657,0

In [17]:
dados_aleatorios_amostra_30 = dados_aleatorios.sample(frac=0.3)
dados_aleatorios_amostra_30

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,inadimplente
7748,-0.974294,2.278220,-2.587410,1.803004,-0.711160,1.062033,0.836548,0.433727,-0.143426,-1.323319,0
2314,0.673568,1.479331,-0.429680,-1.611667,0.295431,2.714077,-1.777063,-0.415003,-4.012963,-1.574336,0
6834,2.864890,1.418480,1.711961,2.205789,-0.218775,-0.525816,-0.870040,-1.181628,-1.941939,-1.656308,1
7921,-0.202627,2.660910,-1.647571,-0.848115,0.580156,2.136134,-0.468067,-0.119815,-3.682986,-2.883215,1
9779,-0.021501,-1.905653,2.507916,-2.813837,-1.112930,0.055447,-0.288964,1.961890,-3.009109,-1.431109,0
...,...,...,...,...,...,...,...,...,...,...,...
3741,-0.268810,-1.566343,0.531537,2.326592,0.025962,-0.867090,-0.844306,-1.467421,0.462384,-1.696898,0
2962,-2.683306,0.237559,-3.142242,-0.802897,-1.233824,1.885607,-0.540288,0.241647,-0.057425,-0.975326,1
1156,0.586475,2.328593,-3.658535,2.919581,-0.075211,1.488030,-2.003967,-0.853131,3.156569,2.409001,0
3128,0.183727,0.785163,-0.616959,-2.538017,1.295812,0.053338,-0.982054,0.776916,-0.435367,0.112229,0
6642,1.282819,1.191544,-2.621694,1.399405,0.025164,-2.654386,-3.590733,-0.272805,5.175452,1.146727,0

In [22]:
# Calcula e imprime a proporção entre o tamanho de dados_aleatorios_amostra_30 e dados_aleatorios, representando a divisão de validação/teste
print("Tamanho da divisão de validação / teste: %.1f" % (len(dados_aleatorios_amostra_30) / len(dataset)))

Tamanho da divisão de validação / teste: 0.3

## Separação do dataset em treino, teste e validação

In [21]:
# Cria o conjunto de TESTE selecionando aleatoriamente
# 50% dos registros do dataframe original.

# sample(frac=0.5):
# - frac=0.5 indica que queremos 50% das linhas
# - a seleção ocorre de forma aleatória
# - o resultado é armazenado em "dados_teste"

# Objetivo:
# O conjunto de teste será utilizado futuramente para
# avaliar o desempenho do modelo em dados que ele nunca viu.
dados_teste = dados_aleatorios_amostra_30.sample(frac=0.5)


# Cria o conjunto de VALIDAÇÃO removendo do dataframe original
# todas as linhas que já foram selecionadas para o conjunto de teste.

# drop(dados_teste.index):
# - remove os índices presentes em "dados_teste"
# - garante que não existam registros duplicados
#   entre teste e validação

# Objetivo:
# O conjunto de validação pode ser utilizado para ajustar
# hiperparâmetros, comparar modelos ou validar métricas
# antes da avaliação final.
dados_validacao = dados_aleatorios_amostra_30.drop(dados_teste.index)

# Cria o conjunto de TREINO.

# Neste ponto existe um erro de sintaxe/lógica:
# "dados_aleatorios(...)" aparenta ser uma função,
# porém provavelmente o objetivo era selecionar os dados
# restantes para treino.
# O correto dependerá da estratégia desejada.

# Objetivo:
# O conjunto de treino é utilizado para ensinar o modelo,
# permitindo que ele aprenda padrões e relações existentes
# nos dados.
dados_treino = dataset.drop(dados_aleatorios_amostra_30.index)

In [23]:
# Verifica a prevalência de cada subconjunto e imprime os resultados
print(
    "Teste(n = %d): %.3f"
    % (len(dados_teste), calcula_prevalencia(dados_teste.inadimplente.values))
)
print(
    "Validação(n = %d): %.3f"
    % (len(dados_validacao), calcula_prevalencia(dados_validacao.inadimplente.values))
)
print(
    "Treino(n = %d): %.3f"
    % (len(dados_treino), calcula_prevalencia(dados_treino.inadimplente.values))
)

Teste(n = 1500): 0.195
Validação(n = 1500): 0.209
Treino(n = 7000): 0.202

# Balanceamento de Classe

In [24]:
dados_teste.shape, dados_treino.shape, dados_validacao.shape

((1500, 11), (7000, 11), (1500, 11))

In [25]:
dados_treino['inadimplente'].value_counts()

inadimplente
0    5586
1    1414
Name: count, dtype: int64

In [26]:
# Cria uma variável booleana 'indice' que indica True para linhas onde TARGET é igual a 1 no DataFrame df_treino
indice = dados_treino['inadimplente']== 1

In [27]:
# Define valores positivos e negativos do índice
dados_treino_positivo = dados_treino.loc[indice]    # Cria um DataFrame df_train_pos contendo apenas as linhas onde 'indice' é True, ou seja, onde a TARGET é igual a 1 em dados_treino
dados_treino_negativo = dados_treino.loc[~indice]   # Cria um DataFrame df_train_neg contendo apenas as linhas onde 'indice' é False, ou seja, onde a TARGET não é igual a 1 em dados_treino

In [28]:
# Calcula o valor mínimo entre o número de linhas em dados_treino_positivo e dados_treino_negativo usando a função np.min() do numpy
valor_minimo = np.min([len(dados_treino_positivo), len(dados_treino_negativo)])
valor_minimo

np.int64(1414)

In [29]:
# Cria um DataFrame df_treino_final concatenando amostras aleatórias de dados_treino_positivo e dados_treino_negativo, com tamanho mínimo igual a valor_minimo, mantendo um estado aleatório consistente
dados_treino_final = pd.concat([dados_treino_positivo.sample(n = valor_minimo, random_state = 69), 
                             dados_treino_negativo.sample(n = valor_minimo, random_state = 69)], 
                            axis = 0, 
                            ignore_index = True)

In [30]:
# Embaralha as linhas do DataFrame dados_treino_final mantendo um estado aleatório consistente e reinicia os índices sem adicionar uma coluna para os índices antigos
dados_treino_final = dados_treino_final.sample(n = len(dados_treino_final), random_state = 69).reset_index(drop = True)

In [31]:
dados_treino_final.shape

(2828, 11)

In [32]:
dados_treino_final['inadimplente'].value_counts()

inadimplente
1    1414
0    1414
Name: count, dtype: int64

In [33]:
# Calcula e imprime a prevalência da classe positiva (inadimplente) no DataFrame df_treino_final, com três casas decimais
print('Balanceamento em Treino(n = %d): %.3f'%(len(dados_treino_final), 
                                               calcula_prevalencia(dados_treino_final['inadimplente'].values)))

Balanceamento em Treino(n = 2828): 0.500